### ISSUE TITLE
[Feature Request] - Backup Only

### ISSUE THREAD

**Issue by danmed** [martadams89/bitwarden-sync#1]
Is there any way this could be used as a backup only solution? 

I'd love to be able to just have an archive of my vault daily for the last year for example ...

**Comment by martadams89** [comment]
If you strip out the "restore" section of the code then this will probably do (or check the v1 branch where I had backup and restore separate)... However, if you're using docker then I think [bruceforce/vaultwarden-backup:latest](https://github.com/Bruceforce/vaultwarden-backup) is probably better...
